// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SaturdayDemo.Infrastructure.DataBase;

namespace SaturdayDemo.Infrastructure.Migrations
{
    [DbContext(typeof(MyDbContext))]
    partial class MyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("SaturdayDemo.Core.entities.BillItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreationDate");

                    b.Property<string>("Market");

                    b.Property<string>("ProductNoName");

                    b.Property<int>("ProductNumber");

                    b.Property<string>("Shop");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.ToTable("BillItems");
                });
#pragma warning restore 612, 618
        }
    }
}
